default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") {"127.0.0.1"} %>
  port: <%= ENV.fetch("DATABASE_PORT") {5432} %>
  pool: <%= ENV.fetch("DATABASE_POOL") {5} %>
  username: <%= ENV.fetch("DATABASE_USERNAME") {"postgres"} %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") {""} %>

development:
  <<: *default
  database: obeder_development

test:
  <<: *default
  database: obeder_test

production:
  <<: *default
  database: obeder_production
  host: db
